baseURL = "/"
languageCode = "en-us"
title = "the way we R"
author = "Zauad Shahreer Abeer"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false
canonifyURLs = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
    
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    
[params]
    description = "of R, life & some randomness"
    footer = "<a href='/about' style = 'font-size:17px; font-style:italic;' class='a-list'>&copy; Zauad Shahreer Abeer</a>"
    disable_highlight = true
    highlightjsVersion = ""
    highlightjsCDN = ""
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = ""
    headerPic = "/img/background-header.png"
    

[params.font]
    body = "Cooper"
    heading = "Cooper"
    code = "Operator Mono"
    arabic = "Amiri"
    bengali = "Apona"
    bodyColor = "#3d3d3d"
    linkColor = "#3a4145"
    greyColor = "#918D8F"
    redColor = "#ed5032"
    
[taxonomies]
    category = "categories"
    tag = "tags"
  
