---
title: চলে গেল আরও একটি বছর
author: আবু মুহাম্মাদ / ০১-০১-২০২১
date: '2021-01-01'
slug: চলে-গেল-আরও-একটি-বছর
categories:
  - life
tags: []
---

```{css, echo=FALSE}
h1, h3, p {
  font-family: var(--bengali) !important;
}

.date {
  display: none;
}
```


<p style = "font-family:Amiri !important; font-size:22px;">
الحمد لله رب العالمين، و العاقبة للمتقين،و الصلاة على رسوله محمدٍ و آله و أصحابه أجمعين، أما بعد
</p>



চলে গেল আরও একটি বছর। 
দশ বছর আগে এমন দিনে গায়ে থাকত সাদা-নেভি ব্লু পোশাক, অহংকারের দুর্গন্ধ তার মাঝে।   
এখন গায়ে থাকে একটা চাদর। তবে সে দুর্গন্ধটা রয়েই গেছে। আতর দিয়ে সেটা ঢাকার একটু চেষ্টা।  
তখন ফিকির থাকত উদযাপন করার। এখন প্রশ্ন হয়, কেন? 

চলে গেল আরও একটি বছর। নতুন বছরের আনন্দ, নাকি মৃত্যুর দিকে আরও এক বছর এগিয়ে যাওয়ার বাস্তবতা?  
ধেয়ে চলেছি অবাধ গতিতে, নদীর স্রোতের মত, গন্তব্যের দিকে ; এটা তার প্রস্তুতি।  
চলে যাওয়া বছরটায় সে প্রস্তুতি কতটুকু হল? গত পাঁচ বছরে? গত দশ বছরে?  

> হে পথিক, আমার ভয় হয় তুমি যে মক্কা পৌঁছাতে পারবে না, কেননা তুমি তুর্কিস্তানের পথে চলেছ।   

হয়ত এভাবে চলে যাবে আরও দশ বছর, আল্লাহ তায়ালা চাইলে।  
দশ বছর পর পেছনে ফিরে তাকালে কী দেখতে পাব?  
সেই একই অন্ধকারের চিত্র? নাকি আলো! আপন সৃষ্টির উদ্দেশ্যের পথে হাঁটার আলো। মালিকের সন্তুষ্টির আশার আলো।  
সেই সিদ্ধান্ত নেয়ার দিন আজ। বছর শুভ হয় নিজেকে সঠিক পথে চালানোর দ্বারা। নতুবা মানুষের দুআ সব বিফল।  

পেছনের কৃতকর্মের জন্য তওবা-ইস্তেগফার, রোনাজারি, আনে ওয়ালা দিনের জন্য নিজেকে প্রস্তুত করা।  
মালিকের হুকুম মত চলা, গুনাহ ছেড়ে দেয়ার শক্ত প্রতিজ্ঞা করা, এটা হওয়া উচিত আজকের দিনের শিক্ষা।  
উদ্দেশ্য তো একটাই, মালিক কীভাবে আমার উপর সন্তুষ্ট হয়ে যায়।  
ব্যাস, সফলতার সংজ্ঞা এটুকুই।  
 
